pull_request_rules:
  - name: Automatic merge for Dependabot pull requests or Flake updates
    conditions:
      - or:
          - author=github-actions[bot]
          - author=dependabot[bot]
    actions:
      merge:
        method: squash
  - name: Automatic update to the main branch for pull requests
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # skip GH draft PRs
      - -author=dependabot[bot] # skip dependabot PRs
    actions:
      update:
